"""two_players_in_game

Revision ID: 63d662fbc764
Revises: ec442cf8b6d2
Create Date: 2024-01-11 20:40:05.060494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d662fbc764'
down_revision = 'ec442cf8b6d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('icon_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id')
    )
    op.add_column('field', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'field', 'player', ['player_id'], ['id'])
    op.add_column('game', sa.Column('player1_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_admin_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_player_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['player2_id'], ['id'])
    op.create_foreign_key(None, 'game', 'user', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['player1_id'], ['id'])
    op.drop_column('game', 'player_id')
    op.drop_column('game', 'player_moves')
    op.add_column('player', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('remaining_moves', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('used_moves', sa.Integer(), nullable=False))
    op.drop_constraint('player_auth_id_key', 'player', type_='unique')
    op.create_foreign_key(None, 'player', 'user', ['user_id'], ['id'])
    op.drop_column('player', 'name')
    op.drop_column('player', 'auth_id')
    op.drop_column('player', 'icon_link')
    op.add_column('prize', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('prize_admin_id_fkey', 'prize', type_='foreignkey')
    op.drop_constraint('prize_player_id_fkey', 'prize', type_='foreignkey')
    op.create_foreign_key(None, 'prize', 'user', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'prize', 'user', ['user_id'], ['id'])
    op.drop_column('prize', 'player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prize', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prize', type_='foreignkey')
    op.drop_constraint(None, 'prize', type_='foreignkey')
    op.create_foreign_key('prize_player_id_fkey', 'prize', 'player', ['player_id'], ['id'])
    op.create_foreign_key('prize_admin_id_fkey', 'prize', 'player', ['admin_id'], ['id'])
    op.drop_column('prize', 'user_id')
    op.add_column('player', sa.Column('icon_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('auth_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_unique_constraint('player_auth_id_key', 'player', ['auth_id'])
    op.drop_column('player', 'used_moves')
    op.drop_column('player', 'remaining_moves')
    op.drop_column('player', 'user_id')
    op.add_column('game', sa.Column('player_moves', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_player_id_fkey', 'game', 'player', ['player_id'], ['id'])
    op.create_foreign_key('game_admin_id_fkey', 'game', 'player', ['admin_id'], ['id'])
    op.drop_column('game', 'player2_id')
    op.drop_column('game', 'player1_id')
    op.drop_constraint(None, 'field', type_='foreignkey')
    op.drop_column('field', 'player_id')
    op.drop_table('user')
    # ### end Alembic commands ###
