"""unique_boat

Revision ID: 8fe33e1a766e
Revises: 1b528ebb5f63
Create Date: 2024-02-08 22:08:40.036840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe33e1a766e'
down_revision = '1b528ebb5f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'boat', ['prize_id'])
    op.create_unique_constraint(None, 'field', ['boat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field', type_='unique')
    op.drop_constraint(None, 'boat', type_='unique')
    # ### end Alembic commands ###
