version: "3.3"

services:
  app:
    build:
      context: .
    container_name: game_api
    restart: always
    command: >
        sh -c "python cli.py game --manager uvicorn --host 0.0.0.0 --port ${API_PORT} --workers 4"
    env_file:
      - .env.example
    ports:
     - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    hostname: db
    container_name: game_db
    env_file:
      - .env.example
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
